name: "CI"

on:
  push:
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: "Test (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    env:
      SASS_VERSION: "1.80.3"
      DART_SASS_SHA_LINUX: "7c933edbad0a7d389192c5b79393485c088bd2c4398e32f5754c32af006a9ffd"
      DART_SASS_SHA_WINDOWS: "0bc4708b37cd1bac4740e83ac5e3176e66b774f77fd5dd364da5b5cfc9bfb469"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Go"
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.x"
          check-latest: true
          cache: true
      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          check-latest: true
      - name: "Setup Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.5"
      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: "Install mage"
        run: |
          go install github.com/magefile/mage@v1.15.0
      - name: "Install staticcheck"
        if: "${{ runner.os == 'Linux' }}"
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: "Install gotmplfmt"
        if: "${{ runner.os == 'Linux' }}"
        run: |
          go install github.com/gohugoio/gotmplfmt@latest
      - name: "Install dart-sass Linux"
        if: "${{ runner.os == 'Linux' }}"
        run: |
          echo "Install Dart Sass version ${SASS_VERSION} ..."
          curl -LJO "https://github.com/sass/dart-sass/releases/download/${SASS_VERSION}/dart-sass-${SASS_VERSION}-linux-x64.tar.gz"
          echo "${DART_SASS_SHA_LINUX}  dart-sass-${SASS_VERSION}-linux-x64.tar.gz" | sha256sum -c
          tar -xvf "dart-sass-${SASS_VERSION}-linux-x64.tar.gz"
          echo "$GITHUB_WORKSPACE/dart-sass/" >> $GITHUB_PATH
      - name: "Install dart-sass Windows"
        if: "${{ runner.os == 'Windows' }}"
        run: |
          echo "Install Dart Sass version ${env:SASS_VERSION} ..."
          curl -LJO "https://github.com/sass/dart-sass/releases/download/${env:SASS_VERSION}/dart-sass-${env:SASS_VERSION}-windows-x64.zip"
          Expand-Archive -Path "dart-sass-${env:SASS_VERSION}-windows-x64.zip" -DestinationPath .
          echo "$env:GITHUB_WORKSPACE/dart-sass/" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf-8 -Append
      - name: "Install asciidoctor"
        run: |
          gem install asciidoctor -v 2.0.26
          gem install asciidoctor-diagram -v 3.1.0
      - name: "Install GoAT"
        run: |
          go install github.com/blampe/goat/cmd/goat@177de93b192b8ffae608e5d9ec421cc99bf68402
      - name: "Install docutils"
        run: |
          pip install docutils
      - name: "Install pandoc Linux"
        if: "${{ runner.os == 'Linux' }}"
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pandoc
      - name: "Install pandoc Windows"
        if: "${{ runner.os == 'Windows' }}"
        run: |
          choco install pandoc
      - name: "Install mingw"
        if: "${{ runner.os == 'Windows' }}"
        run: |
          choco install mingw
      - name: "Check embedded go template formatting"
        if: "${{ runner.os == 'Linux' }}"
        run: "diff <(gotmplfmt -d tpl/tplimpl/embedded/templates) <(printf '')"
      - name: "Run staticcheck"
        if: "${{ runner.os == 'Linux' }}"
        run: |
          staticcheck ./...
      - name: "Check"
        if: "${{ runner.os != 'Windows' }}"
        env:
          HUGO_BUILD_TAGS: "extended,withdeploy"
        run: |
          sass --version
          mage -v check
      - name: "Test"
        if: "${{ runner.os == 'Windows' }}"
        env:
          HUGO_BUILD_TAGS: "extended,withdeploy"
        run: |
          mage -v test